import { GradeSection, PlanTask } from '../types';

// =======================================================================
// GRADE 2A TASKS (Strictly mapped to G2A timetable periods)
// =======================================================================
export const TASKS_2A: PlanTask[] = [
  // ---------------- SUNDAY (2A) ----------------
  // P1: PE | P2: Social | P3: ICT | P4: Arts | P5&6: English | P7: Arabic | P8: Math
  {
    id: '2a-sun-p2-soc',
    day: 'sunday',
    subjectId: 'social_studies',
    section: '2A',
    period: 2,
    type: 'classwork',
    title: 'الوحدة الأولى: مدرستي وبيئتي - قواعد الفصل والمدرسة',
    details: 'الحصة 2 (8:35 - 9:25): التعرف على مبنى المدرسة وقواعد السلوك الإيجابي',
    pages: 'كتاب الدراسات الاجتماعية ص 4-5',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-sun-p3-ict',
    day: 'sunday',
    subjectId: 'ict',
    section: '2A',
    period: 3,
    type: 'classwork',
    title: 'Lesson Title: Introducing the keyboard',
    details: 'Session 1: identify the keyboard parts; describe the use of special keys including number keys, Enter, Space Bar, Shift, Control, Backspace, Caps Lock, and Delete.',
    linkUrl: 'https://www.youtube.com/watch?v=6unZgmlAavQ',
    pages: 'Classwork: Week 1 pages 10 & 12; Homework: Page 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-sun-p5-eng',
    day: 'sunday',
    subjectId: 'english',
    section: '2A',
    period: 5,
    type: 'classwork',
    title: 'Connect Plus: Unit 1 - Welcome Back & School Words',
    details: 'الحصة 5 & 6 (11:25 - 13:05): Introduction to Unit 1, vocabulary, classroom rules & objects',
    pages: 'Student Book pp. 2-5',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-sun-p7-arb',
    day: 'sunday',
    subjectId: 'arabic',
    section: '2A',
    period: 7,
    type: 'classwork',
    title: 'نص الاستماع: أنا أستطيع - مراجعة الحركات القصيرة',
    details: 'الحصة 7 (13:25 - 14:15): الاستماع للنص ومناقشة المعاني وكتابة الكلمات بكشكول الفصل',
    pages: 'كتاب الطالب ص 6-8',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-sun-p8-math',
    day: 'sunday',
    subjectId: 'math',
    section: '2A',
    period: 8,
    type: 'classwork',
    title: 'Welcome Day - Introduction to Block 1 Math',
    details: 'الحصة 8 (14:15 - 15:05): Maths Grade 2 Welcome day & intro to Block 1 numbers',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- MONDAY (2A) ----------------
  // P1: Music | P2: Math | P3: PE | P4: Science | P5&6: Arabic | P7: ICT | P8: English
  {
    id: '2a-mon-p1-mus',
    day: 'monday',
    subjectId: 'music',
    section: '2A',
    period: 1,
    type: 'classwork',
    title: 'النشيد الوطني والتدريب على الإيقاعات الموسيقية',
    details: 'الحصة 1 (7:45 - 8:35): حفظ وترديد النشيد الوطني والتعرف على النغمات الأساسية',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-mon-p2-math',
    day: 'monday',
    subjectId: 'math',
    section: '2A',
    period: 2,
    type: 'classwork',
    title: 'Unit 1: Counting numbers up to 100',
    details: 'الحصة 2 (8:35 - 9:25): Counting in tens and ones up to 100',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-mon-p2-math-sup',
    day: 'monday',
    subjectId: 'math',
    section: '2A',
    period: 2,
    type: 'supplies',
    title: 'Math Tools: Whiteboard & 100 Chart',
    details: 'إحضار السبورة البيضاء الصغيرة والماركر ومخطط الـ 100',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-mon-p4-sci',
    day: 'monday',
    subjectId: 'science',
    section: '2A',
    period: 4,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Lab Safety',
    details: 'الحصة 4 (10:35 - 11:25): Introduction to Sound Sources & Lab Safety Rules',
    pages: 'Student Book pp. 10-12',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-mon-p5-arb',
    day: 'monday',
    subjectId: 'arabic',
    section: '2A',
    period: 5,
    type: 'classwork',
    title: 'الحركات القصيرة والطويلة وتدريبات التنوين',
    details: 'الحصة 5 & 6 (11:25 - 13:05): التمييز بين الفتح والضم والكسر والتنوين بالفتح والضم والكسر',
    pages: 'كشكول الحصة ص 10',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-mon-p7-ict',
    day: 'monday',
    subjectId: 'ict',
    section: '2A',
    period: 7,
    type: 'classwork',
    title: 'QWERTY keyboard and home-row typing',
    details: 'Session 2: explain the meaning of the QWERTY keyboard; use the keyboard home-row keys to type fast.',
    linkUrl: 'https://youtu.be/Jbgv_XPoPnk?si=CGtLbxGDK1v82cB2',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-mon-p8-eng',
    day: 'monday',
    subjectId: 'english',
    section: '2A',
    period: 8,
    type: 'classwork',
    title: 'Phonics: Short Vowels (a, e, i, o, u) & Blends',
    details: 'الحصة 8 (14:15 - 15:05): Pronouncing short vowels and reading practice words',
    pages: 'Activity Book p. 6',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- TUESDAY (2A) ----------------
  // P1&2: English | P3&4: Math | P5: Religion | P6: French | P7: Arts | P8: Arabic
  {
    id: '2a-tue-p1-eng',
    day: 'tuesday',
    subjectId: 'english',
    section: '2A',
    period: 1,
    type: 'classwork',
    title: 'Grammar: Simple Sentences & Action Verbs',
    details: 'الحصة 1 & 2 (7:45 - 9:25): Building complete sentences with subject and verb',
    pages: 'Connect Plus Sheet 1',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-tue-p3-math',
    day: 'tuesday',
    subjectId: 'math',
    section: '2A',
    period: 3,
    type: 'classwork',
    title: 'Unit 1: Place value and value - Partition & recombine',
    details: 'الحصة 3 & 4 (9:45 - 11:25): Partitioning two-digit numbers into tens and ones',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-tue-p3-math-hw',
    day: 'tuesday',
    subjectId: 'math',
    section: '2A',
    period: 3,
    type: 'homework',
    title: 'Math Homework: Page 81',
    details: 'حل تدريبات القيمة المكانية ص 81 في كتاب الرياضيات',
    pages: 'Page 81',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-tue-p5-rel',
    day: 'tuesday',
    subjectId: 'religion',
    section: '2A',
    period: 5,
    type: 'classwork',
    title: 'الله ربنا وخالقنا - فضل شكر النعم والآداب اليومية',
    details: 'الحصة 5 (11:25 - 12:15): التعرف على نعم الله وآداب الشكر والتعامل الطيب',
    pages: 'كتاب التربية الدينية ص 6-9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-tue-p6-fr',
    day: 'tuesday',
    subjectId: 'french',
    section: '2A',
    period: 6,
    type: 'classwork',
    title: 'Cours 1: Brise glace - Des activités pour briser la glace',
    details: 'الحصة 6 (12:15 - 13:05): Le premier cours: activités d\'accueil, salutations et brise-glace',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-tue-p8-arb',
    day: 'tuesday',
    subjectId: 'arabic',
    section: '2A',
    period: 8,
    type: 'classwork',
    title: 'المدود والتاء المربوطة والمفتوحة',
    details: 'الحصة 8 (14:15 - 15:05): التمييز بين التاء المربوطة والهاء والتاء المفتوحة',
    pages: 'كتاب الطالب ص 14',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- WEDNESDAY (2A) ----------------
  // P1: Math | P2: Science | P3: ICT | P4: Social | P5: French | P6: Arabic | P7&8: English
  {
    id: '2a-wed-p1-math',
    day: 'wednesday',
    subjectId: 'math',
    section: '2A',
    period: 1,
    type: 'classwork',
    title: 'Unit 1: Comparing and ordering numbers',
    details: 'الحصة 1 (7:45 - 8:35): Using greater than, less than, and equal symbols (<, >, =)',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p2-sci',
    day: 'wednesday',
    subjectId: 'science',
    section: '2A',
    period: 2,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Sound is a vibration',
    details: 'الحصة 2 (8:35 - 9:25): Understanding how sound travels through vibrations',
    pages: 'Classwork Page 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p2-sci-hw',
    day: 'wednesday',
    subjectId: 'science',
    section: '2A',
    period: 2,
    type: 'homework',
    title: 'Science Homework: Page 16',
    details: 'Complete homework exercises on vibrations and sound sources Page 16',
    pages: 'Page 16',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p3-ict',
    day: 'wednesday',
    subjectId: 'ict',
    section: '2A',
    period: 3,
    type: 'classwork',
    title: 'Arabic and English keyboard layouts; health and safety',
    details: 'Session 3: differentiate between Arabic and English keyboard layouts; switch between Arabic and English keyboard layouts; discuss health and safety aspects when using the keyboard.',
    linkUrl: 'https://youtu.be/6unZgmlAavQ?si=Dx3Oo2cXlXrqQVXS',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p4-soc',
    day: 'wednesday',
    subjectId: 'social_studies',
    section: '2A',
    period: 4,
    type: 'classwork',
    title: 'دوري ومسؤولياتي في الفصل والمدرسة',
    details: 'الحصة 4 (10:35 - 11:25): حل تدريبات كتاب الدراسات الاجتماعية حول النظافة والمحافظة على أثاث الفصل',
    pages: 'كتاب الدراسات الاجتماعية ص 8',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p5-fr',
    day: 'wednesday',
    subjectId: 'french',
    section: '2A',
    period: 5,
    type: 'classwork',
    title: 'Cours 2: Saluer et se présenter - Révision générale',
    details: 'الحصة 5 (11:25 - 12:15): Bonjour, comment tu t\'appelles ? De page 3 à page 7 (Fiche de classe)',
    pages: 'De page 3 à 7',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p6-arb',
    day: 'wednesday',
    subjectId: 'arabic',
    section: '2A',
    period: 6,
    type: 'classwork',
    title: 'ضمائر المتكلم والمخاطب (أنا - نحن - أنتَ - أنتِ)',
    details: 'الحصة 6 (12:15 - 13:05): تركيب جمل صحيحة واستخدام الضمائر المناسبة',
    pages: 'كشكول الحصة ص 16',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-wed-p7-eng',
    day: 'wednesday',
    subjectId: 'english',
    section: '2A',
    period: 7,
    type: 'classwork',
    title: 'Reading Comprehension & Guided Writing',
    details: 'الحصة 7 & 8 (13:25 - 15:05): Short story reading, understanding main idea, and sentence building',
    pages: 'Connect Plus Student Book pp. 8-9',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- THURSDAY (2A) ----------------
  // P1: English | P2: Music | P3: Religion | P4: Arabic | P5: French | P6: Math | P7: Social | P8: Science
  {
    id: '2a-thu-p1-eng',
    day: 'thursday',
    subjectId: 'english',
    section: '2A',
    period: 1,
    type: 'classwork',
    title: 'Weekly Spelling & Review Story',
    details: 'الحصة 1 (7:45 - 8:35): Dictation of target words and weekly grammar wrap-up',
    pages: 'Activity Book p. 11',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p2-mus',
    day: 'thursday',
    subjectId: 'music',
    section: '2A',
    period: 2,
    type: 'classwork',
    title: 'الأناشيد المدرسية وتمييز الإيقاعات السريعة والبطيئة',
    details: 'الحصة 2 (8:35 - 9:25): تدريبات الغناء الجماعي والتناغم الموسيقي',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p3-rel',
    day: 'thursday',
    subjectId: 'religion',
    section: '2A',
    period: 3,
    type: 'classwork',
    title: 'آداب الاستئذان وبر الوالدين وحفظ الآيات / الترانيم',
    details: 'الحصة 3 (9:45 - 10:35): تطبيق عملي على السلوك القويم في البيت والمدرسة',
    pages: 'كتاب التربية الدينية ص 12',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p4-arb',
    day: 'thursday',
    subjectId: 'arabic',
    section: '2A',
    period: 4,
    type: 'classwork',
    title: 'تطبيقات لغوية وإملاء الكلمات الأسبوعية',
    details: 'الحصة 4 (10:35 - 11:25): إملاء أسبوعي على الحركات والمدود وتصحيح الكلمات',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p5-fr',
    day: 'thursday',
    subjectId: 'french',
    section: '2A',
    period: 5,
    type: 'classwork',
    title: 'Cours 3: Les fournitures scolaires - Révision générale',
    details: 'الحصة 5 (11:25 - 12:15): Le stylo, le cahier, la trousse, la gomme. De page 8 à page 9 (Fiche de classe)',
    pages: 'De page 8 à 9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p6-math',
    day: 'thursday',
    subjectId: 'math',
    section: '2A',
    period: 6,
    type: 'classwork',
    title: 'Unit 1: 1 more \\ 1 less & estimation',
    details: 'الحصة 6 (12:15 - 13:05): Estimating quantities and finding 1 more / 1 less than given number',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p6-math-hw',
    day: 'thursday',
    subjectId: 'math',
    section: '2A',
    period: 6,
    type: 'homework',
    title: 'Math Homework: Page 80 & Page 84 (Q.1 only)',
    details: 'حل تدريبات صفحة 80 وصفحة 84 السؤال الأول فقط في كتاب الرياضيات',
    pages: 'Page 80, 84 Q.1',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p7-soc',
    day: 'thursday',
    subjectId: 'social_studies',
    section: '2A',
    period: 7,
    type: 'classwork',
    title: 'بيئتي المحيطة ومعالم وطني مصر',
    details: 'الحصة 7 (13:25 - 14:15): صور ومظاهر البيئة المصرية والمدن الساحلية والريفية',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2a-thu-p8-sci',
    day: 'thursday',
    subjectId: 'science',
    section: '2A',
    period: 8,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Sound is a vibration (Hands-on exploration)',
    details: 'الحصة 8 (14:15 - 15:05): Hands-on vibration activities & sound exploration (Class A-B-C)',
    isDone: false,
    createdAt: Date.now(),
  },
];

// =======================================================================
// GRADE 2B TASKS (Strictly mapped to G2B timetable periods)
// =======================================================================
export const TASKS_2B: PlanTask[] = [
  // ---------------- SUNDAY (2B) ----------------
  // P1: French | P2: Math | P3: Arabic | P4: Science | P5&6: English | P7: ICT | P8: Music
  {
    id: '2b-sun-p1-fr',
    day: 'sunday',
    subjectId: 'french',
    section: '2B',
    period: 1,
    type: 'classwork',
    title: 'Cours 1: Brise glace - Des activités pour briser la glace',
    details: 'الحصة 1 (7:45 - 8:35): Le premier cours: activités d\'accueil et de brise-glace',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-sun-p2-math',
    day: 'sunday',
    subjectId: 'math',
    section: '2B',
    period: 2,
    type: 'classwork',
    title: 'Welcome Day - Introduction to Block 1 Math',
    details: 'الحصة 2 (8:35 - 9:25): Maths Grade 2 Welcome day & intro to Block 1 numbers',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-sun-p3-arb',
    day: 'sunday',
    subjectId: 'arabic',
    section: '2B',
    period: 3,
    type: 'classwork',
    title: 'نص الاستماع: أنا أستطيع - قصة البداية والمقدمة',
    details: 'الحصة 3 (9:45 - 10:35): الاستماع للنص ومناقشة المعاني وكتابة الكلمات بكشكول الفصل',
    pages: 'كتاب الطالب ص 6-8',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-sun-p4-sci',
    day: 'sunday',
    subjectId: 'science',
    section: '2B',
    period: 4,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Lab Safety (Class 2B)',
    details: 'الحصة 4 (10:35 - 11:25): Introduction to Sound Sources and laboratory safety rules',
    pages: 'Student Book pp. 10-12',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-sun-p5-eng',
    day: 'sunday',
    subjectId: 'english',
    section: '2B',
    period: 5,
    type: 'classwork',
    title: 'Connect Plus: Unit 1 - Welcome Back & School Words',
    details: 'الحصة 5 & 6 (11:25 - 13:05): Introduction to Unit 1, vocabulary, classroom rules & objects',
    pages: 'Student Book pp. 2-5',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-sun-p7-ict',
    day: 'sunday',
    subjectId: 'ict',
    section: '2B',
    period: 7,
    type: 'classwork',
    title: 'Lesson Title: Introducing the keyboard',
    details: 'Session 1: identify the keyboard parts; describe the use of special keys including number keys, Enter, Space Bar, Shift, Control, Backspace, Caps Lock, and Delete.',
    linkUrl: 'https://www.youtube.com/watch?v=6unZgmlAavQ',
    pages: 'Classwork: Week 1 pages 10 & 12; Homework: Page 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-sun-p8-mus',
    day: 'sunday',
    subjectId: 'music',
    section: '2B',
    period: 8,
    type: 'classwork',
    title: 'النشيد الوطني والتدريب على الإيقاعات الموسيقية',
    details: 'الحصة 8 (14:15 - 15:05): حفظ وترديد النشيد الوطني والتعرف على النغمات الأساسية',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- MONDAY (2B) ----------------
  // P1: Social | P2: PE | P3&4: English | P5&6: Math | P7&8: Arabic
  {
    id: '2b-mon-p1-soc',
    day: 'monday',
    subjectId: 'social_studies',
    section: '2B',
    period: 1,
    type: 'classwork',
    title: 'الوحدة الأولى: مدرستي وبيئتي - قواعد الفصل والمدرسة',
    details: 'الحصة 1 (7:45 - 8:35): التعرف على مبنى المدرسة وقواعد السلوك الإيجابي',
    pages: 'كتاب الدراسات الاجتماعية ص 4-5',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-mon-p3-eng',
    day: 'monday',
    subjectId: 'english',
    section: '2B',
    period: 3,
    type: 'classwork',
    title: 'Phonics: Short Vowels (a, e, i, o, u) & Blends',
    details: 'الحصة 3 & 4 (9:45 - 11:25): Pronouncing short vowels and reading practice words',
    pages: 'Activity Book p. 6',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-mon-p5-math',
    day: 'monday',
    subjectId: 'math',
    section: '2B',
    period: 5,
    type: 'classwork',
    title: 'Unit 1: Counting numbers up to 100',
    details: 'الحصة 5 & 6 (11:25 - 13:05): Counting in tens and ones up to 100',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-mon-p5-math-sup',
    day: 'monday',
    subjectId: 'math',
    section: '2B',
    period: 5,
    type: 'supplies',
    title: 'Math Tools: Whiteboard & 100 Chart',
    details: 'إحضار السبورة البيضاء الصغيرة والماركر ومخطط الـ 100',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-mon-p7-arb',
    day: 'monday',
    subjectId: 'arabic',
    section: '2B',
    period: 7,
    type: 'classwork',
    title: 'الحركات القصيرة والطويلة وتدريبات التنوين',
    details: 'الحصة 7 & 8 (13:25 - 15:05): التمييز بين الفتح والضم والكسر والتنوين بالفتح والضم والكسر',
    pages: 'كشكول الحصة ص 10',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- TUESDAY (2B) ----------------
  // P1: Math | P2: ICT | P3: Arts | P4: French | P5: Religion | P6: English | P7: Music | P8: Arabic
  {
    id: '2b-tue-p1-math',
    day: 'tuesday',
    subjectId: 'math',
    section: '2B',
    period: 1,
    type: 'classwork',
    title: 'Unit 1: Place value and value - Partition & recombine',
    details: 'الحصة 1 (7:45 - 8:35): Partitioning two-digit numbers into tens and ones',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p1-math-hw',
    day: 'tuesday',
    subjectId: 'math',
    section: '2B',
    period: 1,
    type: 'homework',
    title: 'Math Homework: Page 81',
    details: 'حل تدريبات القيمة المكانية ص 81 في كتاب الرياضيات',
    pages: 'Page 81',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p2-ict',
    day: 'tuesday',
    subjectId: 'ict',
    section: '2B',
    period: 2,
    type: 'classwork',
    title: 'QWERTY keyboard and home-row typing',
    details: 'Session 2: explain the meaning of the QWERTY keyboard; use the keyboard home-row keys to type fast.',
    linkUrl: 'https://youtu.be/Jbgv_XPoPnk?si=CGtLbxGDK1v82cB2',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p4-fr',
    day: 'tuesday',
    subjectId: 'french',
    section: '2B',
    period: 4,
    type: 'classwork',
    title: 'Cours 2: Saluer et se présenter - Révision générale',
    details: 'الحصة 4 (10:35 - 11:25): Bonjour, comment tu t\'appelles ? De page 3 à page 7 (Fiche de classe)',
    pages: 'De page 3 à 7',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p5-rel',
    day: 'tuesday',
    subjectId: 'religion',
    section: '2B',
    period: 5,
    type: 'classwork',
    title: 'الله ربنا وخالقنا - فضل شكر النعم والآداب اليومية',
    details: 'الحصة 5 (11:25 - 12:15): التعرف على نعم الله وآداب الشكر والتعامل الطيب',
    pages: 'كتاب التربية الدينية ص 6-9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p6-eng',
    day: 'tuesday',
    subjectId: 'english',
    section: '2B',
    period: 6,
    type: 'classwork',
    title: 'Grammar: Simple Sentences & Action Verbs',
    details: 'الحصة 6 (12:15 - 13:05): Building complete sentences with subject and verb',
    pages: 'Connect Plus Sheet 1',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p7-mus',
    day: 'tuesday',
    subjectId: 'music',
    section: '2B',
    period: 7,
    type: 'classwork',
    title: 'الأناشيد المدرسية والتدريب على النغمات والإيقاع',
    details: 'الحصة 7 (13:25 - 14:15): تمييز النغمات الموسيقية والتدريب الصوتي',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-tue-p8-arb',
    day: 'tuesday',
    subjectId: 'arabic',
    section: '2B',
    period: 8,
    type: 'classwork',
    title: 'المدود والتاء المربوطة والتاء المفتوحة',
    details: 'الحصة 8 (14:15 - 15:05): التمييز بين التاء المربوطة والهاء والتاء المفتوحة',
    pages: 'كتاب الطالب ص 14',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- WEDNESDAY (2B) ----------------
  // P1: English | P2: Social | P3: PE | P4: Arabic | P5: Math | P6: French | P7: Science | P8: Arts
  {
    id: '2b-wed-p1-eng',
    day: 'wednesday',
    subjectId: 'english',
    section: '2B',
    period: 1,
    type: 'classwork',
    title: 'Reading Comprehension & Guided Writing',
    details: 'الحصة 1 (7:45 - 8:35): Short story reading and sentence building',
    pages: 'Connect Plus Student Book pp. 8-9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-wed-p2-soc',
    day: 'wednesday',
    subjectId: 'social_studies',
    section: '2B',
    period: 2,
    type: 'classwork',
    title: 'دوري ومسؤولياتي في الفصل والمدرسة',
    details: 'الحصة 2 (8:35 - 9:25): حل تدريبات كتاب الدراسات الاجتماعية حول النظافة والمحافظة على أثاث الفصل',
    pages: 'كتاب الدراسات الاجتماعية ص 8',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-wed-p4-arb',
    day: 'wednesday',
    subjectId: 'arabic',
    section: '2B',
    period: 4,
    type: 'classwork',
    title: 'ضمائر المتكلم والمخاطب (أنا - نحن - أنتَ - أنتِ)',
    details: 'الحصة 4 (10:35 - 11:25): تركيب جمل صحيحة واستخدام الضمائر المناسبة',
    pages: 'كشكول الحصة ص 16',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-wed-p5-math',
    day: 'wednesday',
    subjectId: 'math',
    section: '2B',
    period: 5,
    type: 'classwork',
    title: 'Unit 1: Comparing and ordering numbers',
    details: 'الحصة 5 (11:25 - 12:15): Using greater than, less than, and equal symbols (<, >, =)',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-wed-p6-fr',
    day: 'wednesday',
    subjectId: 'french',
    section: '2B',
    period: 6,
    type: 'classwork',
    title: 'Cours 3: Les fournitures scolaires - Révision générale',
    details: 'الحصة 6 (12:15 - 13:05): Le stylo, le cahier, la trousse, la gomme. De page 8 à page 9',
    pages: 'De page 8 à 9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-wed-p7-sci',
    day: 'wednesday',
    subjectId: 'science',
    section: '2B',
    period: 7,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Sound is a vibration',
    details: 'الحصة 7 (13:25 - 14:15): Understanding how sound travels through vibrations',
    pages: 'Classwork Page 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-wed-p7-sci-hw',
    day: 'wednesday',
    subjectId: 'science',
    section: '2B',
    period: 7,
    type: 'homework',
    title: 'Science Homework: Page 16',
    details: 'Complete homework exercises on vibrations and sound sources Page 16',
    pages: 'Page 16',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- THURSDAY (2B) ----------------
  // P1: Arabic | P2: Social | P3: Religion | P4: Math | P5&6: English | P7: Science | P8: ICT
  {
    id: '2b-thu-p1-arb',
    day: 'thursday',
    subjectId: 'arabic',
    section: '2B',
    period: 1,
    type: 'classwork',
    title: 'تطبيقات لغوية وإملاء الكلمات الأسبوعية',
    details: 'الحصة 1 (7:45 - 8:35): إملاء أسبوعي على الحركات والمدود وتصحيح الكلمات',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p2-soc',
    day: 'thursday',
    subjectId: 'social_studies',
    section: '2B',
    period: 2,
    type: 'classwork',
    title: 'بيئتي المحيطة ومعالم وطني مصر',
    details: 'الحصة 2 (8:35 - 9:25): صور ومظاهر البيئة المصرية والمدن الساحلية والريفية',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p3-rel',
    day: 'thursday',
    subjectId: 'religion',
    section: '2B',
    period: 3,
    type: 'classwork',
    title: 'آداب الاستئذان وبر الوالدين وحفظ الآيات / الترانيم',
    details: 'الحصة 3 (9:45 - 10:35): تطبيق عملي على السلوك القويم في البيت والمدرسة',
    pages: 'كتاب التربية الدينية ص 12',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p4-math',
    day: 'thursday',
    subjectId: 'math',
    section: '2B',
    period: 4,
    type: 'classwork',
    title: 'Unit 1: 1 more \\ 1 less & estimation',
    details: 'الحصة 4 (10:35 - 11:25): Estimating quantities and finding 1 more / 1 less than given number',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p4-math-hw',
    day: 'thursday',
    subjectId: 'math',
    section: '2B',
    period: 4,
    type: 'homework',
    title: 'Math Homework: Page 80 & Page 84 (Q.1 only)',
    details: 'حل تدريبات صفحة 80 وصفحة 84 السؤال الأول فقط في كتاب الرياضيات',
    pages: 'Page 80, 84 Q.1',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p5-eng',
    day: 'thursday',
    subjectId: 'english',
    section: '2B',
    period: 5,
    type: 'classwork',
    title: 'Weekly Spelling & Review Story',
    details: 'الحصة 5 & 6 (11:25 - 13:05): Dictation of target words and weekly grammar wrap-up',
    pages: 'Activity Book p. 11',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p7-sci',
    day: 'thursday',
    subjectId: 'science',
    section: '2B',
    period: 7,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Sound is a vibration (Hands-on exploration)',
    details: 'الحصة 7 (13:25 - 14:15): Hands-on vibration activities & sound exploration (Class A-B-C)',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2b-thu-p8-ict',
    day: 'thursday',
    subjectId: 'ict',
    section: '2B',
    period: 8,
    type: 'classwork',
    title: 'Arabic and English keyboard layouts; health and safety',
    details: 'Session 3: differentiate between Arabic and English keyboard layouts; switch between Arabic and English keyboard layouts; discuss health and safety aspects when using the keyboard.',
    linkUrl: 'https://youtu.be/6unZgmlAavQ?si=Dx3Oo2cXlXrqQVXS',
    isDone: false,
    createdAt: Date.now(),
  },
];

// =======================================================================
// GRADE 2C TASKS (Strictly mapped to G2C timetable periods)
// =======================================================================
export const TASKS_2C: PlanTask[] = [
  // ---------------- SUNDAY (2C) ----------------
  // P1&2: Math | P3: French | P4: English | P5: ICT | P6: Arabic | P7: Social | P8: PE
  {
    id: '2c-sun-p1-math',
    day: 'sunday',
    subjectId: 'math',
    section: '2C',
    period: 1,
    type: 'classwork',
    title: 'Welcome Day - Introduction to Block 1 Math',
    details: 'الحصة 1 & 2 (7:45 - 9:25): Maths Grade 2 Welcome day & intro to Block 1 numbers',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-sun-p3-fr',
    day: 'sunday',
    subjectId: 'french',
    section: '2C',
    period: 3,
    type: 'classwork',
    title: 'Cours 1: Brise glace - Des activités pour briser la glace',
    details: 'الحصة 3 (9:45 - 10:35): Le premier cours: activités d\'accueil et de brise-glace',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-sun-p4-eng',
    day: 'sunday',
    subjectId: 'english',
    section: '2C',
    period: 4,
    type: 'classwork',
    title: 'Connect Plus: Unit 1 - Welcome Back & School Words',
    details: 'الحصة 4 (10:35 - 11:25): Introduction to Unit 1, vocabulary, classroom rules & objects',
    pages: 'Student Book pp. 2-5',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-sun-p5-ict',
    day: 'sunday',
    subjectId: 'ict',
    section: '2C',
    period: 5,
    type: 'classwork',
    title: 'Lesson Title: Introducing the keyboard',
    details: 'Session 1: identify the keyboard parts; describe the use of special keys including number keys, Enter, Space Bar, Shift, Control, Backspace, Caps Lock, and Delete.',
    linkUrl: 'https://www.youtube.com/watch?v=6unZgmlAavQ',
    pages: 'Classwork: Week 1 pages 10 & 12; Homework: Page 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-sun-p6-arb',
    day: 'sunday',
    subjectId: 'arabic',
    section: '2C',
    period: 6,
    type: 'classwork',
    title: 'نص الاستماع: أنا أستطيع - مراجعة الحركات القصيرة والمدود',
    details: 'الحصة 6 (12:15 - 13:05): الاستماع للنص ومناقشة المعاني وكتابة الكلمات بكشكول الفصل',
    pages: 'كتاب الطالب ص 6-8',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-sun-p7-soc',
    day: 'sunday',
    subjectId: 'social_studies',
    section: '2C',
    period: 7,
    type: 'classwork',
    title: 'الوحدة الأولى: مدرستي وبيئتي - قواعد الفصل والمدرسة',
    details: 'الحصة 7 (13:25 - 14:15): التعرف على مبنى المدرسة وقواعد السلوك الإيجابي',
    pages: 'كتاب الدراسات الاجتماعية ص 4-5',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- MONDAY (2C) ----------------
  // P1&2: Arabic | P3: Social | P4: English | P5: Science | P6: Arts | P7: French | P8: Math
  {
    id: '2c-mon-p1-arb',
    day: 'monday',
    subjectId: 'arabic',
    section: '2C',
    period: 1,
    type: 'classwork',
    title: 'الحركات القصيرة والطويلة وتدريبات التنوين',
    details: 'الحصة 1 & 2 (7:45 - 9:25): التمييز بين الفتح والضم والكسر والتنوين بكشكول الفصل',
    pages: 'كشكول الحصة ص 10',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-mon-p3-soc',
    day: 'monday',
    subjectId: 'social_studies',
    section: '2C',
    period: 3,
    type: 'classwork',
    title: 'دوري ومسؤولياتي في الفصل والمدرسة',
    details: 'الحصة 3 (9:45 - 10:35): حل تدريبات كتاب الدراسات الاجتماعية حول النظافة والمحافظة على أثاث الفصل',
    pages: 'كتاب الدراسات الاجتماعية ص 8',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-mon-p4-eng',
    day: 'monday',
    subjectId: 'english',
    section: '2C',
    period: 4,
    type: 'classwork',
    title: 'Phonics: Short Vowels (a, e, i, o, u) & Blends',
    details: 'الحصة 4 (10:35 - 11:25): Pronouncing short vowels and reading practice words',
    pages: 'Activity Book p. 6',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-mon-p5-sci',
    day: 'monday',
    subjectId: 'science',
    section: '2C',
    period: 5,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Lab Safety',
    details: 'الحصة 5 (11:25 - 12:15): Introduction to Sound Sources & Lab Safety Rules',
    pages: 'Student Book pp. 10-12',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-mon-p7-fr',
    day: 'monday',
    subjectId: 'french',
    section: '2C',
    period: 7,
    type: 'classwork',
    title: 'Cours 2: Saluer et se présenter - Révision générale',
    details: 'الحصة 7 (13:25 - 14:15): Bonjour, comment tu t\'appelles ? De page 3 à page 7 (Fiche de classe)',
    pages: 'De page 3 à 7',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-mon-p8-math',
    day: 'monday',
    subjectId: 'math',
    section: '2C',
    period: 8,
    type: 'classwork',
    title: 'Unit 1: Counting numbers up to 100',
    details: 'الحصة 8 (14:15 - 15:05): Counting in tens and ones up to 100',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-mon-p8-math-sup',
    day: 'monday',
    subjectId: 'math',
    section: '2C',
    period: 8,
    type: 'supplies',
    title: 'Math Tools: Whiteboard & 100 Chart',
    details: 'إحضار السبورة البيضاء الصغيرة والماركر ومخطط الـ 100',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- TUESDAY (2C) ----------------
  // P1: PE | P2: Arabic | P3: Science | P4: Math | P5: Religion | P6: ICT | P7&8: English
  {
    id: '2c-tue-p2-arb',
    day: 'tuesday',
    subjectId: 'arabic',
    section: '2C',
    period: 2,
    type: 'classwork',
    title: 'المدود والتاء المربوطة والمفتوحة',
    details: 'الحصة 2 (8:35 - 9:25): التمييز بين التاء المربوطة والهاء والتاء المفتوحة',
    pages: 'كتاب الطالب ص 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p3-sci',
    day: 'tuesday',
    subjectId: 'science',
    section: '2C',
    period: 3,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Sound is a vibration',
    details: 'الحصة 3 (9:45 - 10:35): Understanding how sound travels through vibrations',
    pages: 'Classwork Page 14',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p3-sci-hw',
    day: 'tuesday',
    subjectId: 'science',
    section: '2C',
    period: 3,
    type: 'homework',
    title: 'Science Homework: Page 16',
    details: 'Complete homework exercises on vibrations and sound sources Page 16',
    pages: 'Page 16',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p4-math',
    day: 'tuesday',
    subjectId: 'math',
    section: '2C',
    period: 4,
    type: 'classwork',
    title: 'Unit 1: Place value and value - Partition & recombine',
    details: 'الحصة 4 (10:35 - 11:25): Partitioning two-digit numbers into tens and ones',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p4-math-hw',
    day: 'tuesday',
    subjectId: 'math',
    section: '2C',
    period: 4,
    type: 'homework',
    title: 'Math Homework: Page 81',
    details: 'حل تدريبات القيمة المكانية ص 81 في كتاب الرياضيات',
    pages: 'Page 81',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p5-rel',
    day: 'tuesday',
    subjectId: 'religion',
    section: '2C',
    period: 5,
    type: 'classwork',
    title: 'الله ربنا وخالقنا - فضل شكر النعم والآداب اليومية',
    details: 'الحصة 5 (11:25 - 12:15): التعرف على نعم الله وآداب الشكر والتعامل الطيب',
    pages: 'كتاب التربية الدينية ص 6-9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p6-ict',
    day: 'tuesday',
    subjectId: 'ict',
    section: '2C',
    period: 6,
    type: 'classwork',
    title: 'QWERTY keyboard and home-row typing',
    details: 'Session 2: explain the meaning of the QWERTY keyboard; use the keyboard home-row keys to type fast.',
    linkUrl: 'https://youtu.be/Jbgv_XPoPnk?si=CGtLbxGDK1v82cB2',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-tue-p7-eng',
    day: 'tuesday',
    subjectId: 'english',
    section: '2C',
    period: 7,
    type: 'classwork',
    title: 'Grammar: Simple Sentences & Action Verbs',
    details: 'الحصة 7 & 8 (13:25 - 15:05): Building complete sentences with subject and verb',
    pages: 'Connect Plus Sheet 1',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- WEDNESDAY (2C) ----------------
  // P1&2: English | P3: French | P4: Social | P5: Music | P6: Arabic | P7: Math | P8: Music
  {
    id: '2c-wed-p1-eng',
    day: 'wednesday',
    subjectId: 'english',
    section: '2C',
    period: 1,
    type: 'classwork',
    title: 'Reading Comprehension & Guided Writing',
    details: 'الحصة 1 & 2 (7:45 - 9:25): Short story reading and sentence building',
    pages: 'Connect Plus Student Book pp. 8-9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-wed-p3-fr',
    day: 'wednesday',
    subjectId: 'french',
    section: '2C',
    period: 3,
    type: 'classwork',
    title: 'Cours 3: Les fournitures scolaires - Révision générale',
    details: 'الحصة 3 (9:45 - 10:35): Le stylo, le cahier, la trousse, la gomme. De page 8 à page 9',
    pages: 'De page 8 à 9',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-wed-p4-soc',
    day: 'wednesday',
    subjectId: 'social_studies',
    section: '2C',
    period: 4,
    type: 'classwork',
    title: 'بيئتي المحيطة ومعالم وطني مصر',
    details: 'الحصة 4 (10:35 - 11:25): صور ومظاهر البيئة المصرية والمدن الساحلية والريفية',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-wed-p5-mus',
    day: 'wednesday',
    subjectId: 'music',
    section: '2C',
    period: 5,
    type: 'classwork',
    title: 'النشيد الوطني والتدريب على الإيقاعات الموسيقية',
    details: 'الحصة 5 (11:25 - 12:15): حفظ وترديد النشيد الوطني والتعرف على النغمات الأساسية',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-wed-p6-arb',
    day: 'wednesday',
    subjectId: 'arabic',
    section: '2C',
    period: 6,
    type: 'classwork',
    title: 'ضمائر المتكلم والمخاطب (أنا - نحن - أنتَ - أنتِ)',
    details: 'الحصة 6 (12:15 - 13:05): تركيب جمل صحيحة واستخدام الضمائر المناسبة',
    pages: 'كشكول الحصة ص 16',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-wed-p7-math',
    day: 'wednesday',
    subjectId: 'math',
    section: '2C',
    period: 7,
    type: 'classwork',
    title: 'Unit 1: Comparing and ordering numbers',
    details: 'الحصة 7 (13:25 - 14:15): Using greater than, less than, and equal symbols (<, >, =)',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-wed-p8-mus',
    day: 'wednesday',
    subjectId: 'music',
    section: '2C',
    period: 8,
    type: 'classwork',
    title: 'الأناشيد المدرسية والتدريب الصوتي الجماعي',
    details: 'الحصة 8 (14:15 - 15:05): تمييز النغمات الموسيقية والتدريب الصوتي',
    isDone: false,
    createdAt: Date.now(),
  },

  // ---------------- THURSDAY (2C) ----------------
  // P1: ICT | P2: Science | P3: Religion | P4&5: English | P6: Math | P7: Arabic | P8: Arts
  {
    id: '2c-thu-p1-ict',
    day: 'thursday',
    subjectId: 'ict',
    section: '2C',
    period: 1,
    type: 'classwork',
    title: 'Arabic and English keyboard layouts; health and safety',
    details: 'Session 3: differentiate between Arabic and English keyboard layouts; switch between Arabic and English keyboard layouts; discuss health and safety aspects when using the keyboard.',
    linkUrl: 'https://youtu.be/6unZgmlAavQ?si=Dx3Oo2cXlXrqQVXS',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-thu-p2-sci',
    day: 'thursday',
    subjectId: 'science',
    section: '2C',
    period: 2,
    type: 'classwork',
    title: 'Unit 1: Sound Sources - Sound is a vibration (Hands-on exploration)',
    details: 'الحصة 2 (8:35 - 9:25): Hands-on vibration activities & sound exploration (Class A-B-C)',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-thu-p3-rel',
    day: 'thursday',
    subjectId: 'religion',
    section: '2C',
    period: 3,
    type: 'classwork',
    title: 'آداب الاستئذان وبر الوالدين وحفظ الآيات / الترانيم',
    details: 'الحصة 3 (9:45 - 10:35): تطبيق عملي على السلوك القويم في البيت والمدرسة',
    pages: 'كتاب التربية الدينية ص 12',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-thu-p4-eng',
    day: 'thursday',
    subjectId: 'english',
    section: '2C',
    period: 4,
    type: 'classwork',
    title: 'Weekly Spelling & Review Story',
    details: 'الحصة 4 & 5 (10:35 - 12:15): Dictation of target words and weekly grammar wrap-up',
    pages: 'Activity Book p. 11',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-thu-p6-math',
    day: 'thursday',
    subjectId: 'math',
    section: '2C',
    period: 6,
    type: 'classwork',
    title: 'Unit 1: 1 more \\ 1 less & estimation',
    details: 'الحصة 6 (12:15 - 13:05): Estimating quantities and finding 1 more / 1 less than given number',
    pages: 'Sheet 1 - Main',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-thu-p6-math-hw',
    day: 'thursday',
    subjectId: 'math',
    section: '2C',
    period: 6,
    type: 'homework',
    title: 'Math Homework: Page 80 & Page 84 (Q.1 only)',
    details: 'حل تدريبات صفحة 80 وصفحة 84 السؤال الأول فقط في كتاب الرياضيات',
    pages: 'Page 80, 84 Q.1',
    isDone: false,
    createdAt: Date.now(),
  },
  {
    id: '2c-thu-p7-arb',
    day: 'thursday',
    subjectId: 'arabic',
    section: '2C',
    period: 7,
    type: 'classwork',
    title: 'تطبيقات لغوية وإملاء الكلمات الأسبوعية',
    details: 'الحصة 7 (13:25 - 14:15): إملاء أسبوعي على الحركات والمدود وتصحيح الكلمات',
    isDone: false,
    createdAt: Date.now(),
  },
];

export const GRADE_TASKS: Record<GradeSection, PlanTask[]> = {
  '2A': TASKS_2A,
  '2B': TASKS_2B,
  '2C': TASKS_2C,
};
